
#nohup ~/.local/bin/snakemake --snakefile ../../Snakefile --cluster "sbatch --nice {cluster.oversubscribe} {cluster.gres}" --cluster-config ../cluster.json --cores 4222 -j 4222 -k --configfile config.fr-en.yaml &

bitextor: /home/s0565741/workspace/github/paracrawl/bitextor.malign

langstat: /home/s0565741/workspace/experiment/issues/paracrawl/langstat/langstats.all.gz
langstatThreshold: 1000000
hostPath: /home/s0565741/workspace/experiment/issues/paracrawl/prevHosts/hosts.fr.gz
linkedHosts: ["/home/s0565741/workspace/experiment/paracrawl/v3/hu-en/permanent"]
linkedHostsAction: link #link #postCrawlExclude #remove

langstatExcludeStrings: /home/s0565741/workspace/github/paracrawl/bitextor.malign/snakemake/langstat-exclude-strings
excludeHostsFile: /home/s0565741/workspace/github/paracrawl/bitextor.malign/snakemake/exclude-hosts
crawlerUserAgent: Mozilla/5.0 (compatible; Paracrawl; +http://statmt.org/paracrawl/robots.html)
httrack: true

temp: /raid0/tmp
permanentDir: /home/s0565741/workspace/experiment/paracrawl/v3/fr-en/permanent
transientDir: /home/s0565741/workspace/experiment/paracrawl/v3/fr-en/transient
lang1: fr
lang2: en
crawlTimeLimit: 43200s
crawlPageLimit: 100000
crawlerNumThreads: 2
crawlTld: false

#mosesDir: /home/s0565741/workspace/github/mosesdecoder
LANG1Tokenizer: "/home/s0565741/workspace/github/paracrawl/bitextor.malign/preprocess/moses/tokenizer/tokenizer.perl -l fr -a -b -q"
LANG2Tokenizer: "/home/s0565741/workspace/github/paracrawl/bitextor.malign/preprocess/moses/tokenizer/tokenizer.perl -l en -a -b -q"
LANG1SentenceSplitter: "/home/s0565741/workspace/github/paracrawl/bitextor.malign/preprocess/moses/ems/support/split-sentences.perl -b -l fr"
LANG2SentenceSplitter: "/home/s0565741/workspace/github/paracrawl/bitextor.malign/preprocess/moses/ems/support/split-sentences.perl -b -l en"
deduped: true
tmx: true
storeRawCorpus: true
elrc: true
documentAligner: externalMT
alignerCmd: "/home/s0565741/workspace/experiment/paracrawl/phi-system/translate-pipe.sh fr"
bleualign: true
docAlignThreshold: 0.1
bleuAlignThreshold: 0.2
maxSizeWARC: 5000
bicleaner: /home/s0565741/workspace/experiment/paracrawl/v3/bicleaner_models/en-fr/training.en-fr.yaml
bicleanerThreshold: 0.7
